"""GICS + TradingView per-ticker classifications.

Pure-Python taxonomy data + fetchers, adjacent to ``watchlists.py``.

Taxonomies:
- ``gics`` — sector / industry_group / industry / sub_industry for S&P 500
  members, rolled up through the embedded 2023 GICS hierarchy.
- ``tv`` — TradingView's ICB-style sector / industry for all US stocks,
  via the scanner API ``screen()``.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any

from pytvtools_core.watchlists import screen

# 273 GICS codes, 2023 edition: {code: {name, parent_code, level_num}}
_GICS_HIERARCHY: dict[str, dict[str, str]] = {
    '10': {"name": 'Energy', "parent_code": '', "level_num": '1'},
    '1010': {"name": 'Energy', "parent_code": '10', "level_num": '2'},
    '101010': {"name": 'Energy Equipment & Services', "parent_code": '1010', "level_num": '3'},
    '10101010': {"name": 'Oil & Gas Drilling', "parent_code": '101010', "level_num": '4'},
    '10101020': {"name": 'Oil & Gas Equipment & Services', "parent_code": '101010', "level_num": '4'},
    '101020': {"name": 'Oil, Gas & Consumable Fuels', "parent_code": '1010', "level_num": '3'},
    '10102010': {"name": 'Integrated Oil & Gas', "parent_code": '101020', "level_num": '4'},
    '10102020': {"name": 'Oil & Gas Exploration & Production', "parent_code": '101020', "level_num": '4'},
    '10102030': {"name": 'Oil & Gas Refining & Marketing', "parent_code": '101020', "level_num": '4'},
    '10102040': {"name": 'Oil & Gas Storage & Transportation', "parent_code": '101020', "level_num": '4'},
    '10102050': {"name": 'Coal & Consumable Fuels', "parent_code": '101020', "level_num": '4'},
    '15': {"name": 'Materials', "parent_code": '', "level_num": '1'},
    '1510': {"name": 'Materials', "parent_code": '15', "level_num": '2'},
    '151010': {"name": 'Chemicals', "parent_code": '1510', "level_num": '3'},
    '15101010': {"name": 'Commodity Chemicals', "parent_code": '151010', "level_num": '4'},
    '15101020': {"name": 'Diversified Chemicals', "parent_code": '151010', "level_num": '4'},
    '15101030': {"name": 'Fertilizers & Agricultural Chemicals', "parent_code": '151010', "level_num": '4'},
    '15101040': {"name": 'Industrial Gases', "parent_code": '151010', "level_num": '4'},
    '15101050': {"name": 'Specialty Chemicals', "parent_code": '151010', "level_num": '4'},
    '151020': {"name": 'Construction Materials', "parent_code": '1510', "level_num": '3'},
    '15102010': {"name": 'Construction Materials', "parent_code": '151020', "level_num": '4'},
    '151030': {"name": 'Containers & Packaging', "parent_code": '1510', "level_num": '3'},
    '15103010': {"name": 'Metal, Glass & Plastic Containers', "parent_code": '151030', "level_num": '4'},
    '15103020': {"name": 'Paper & Plastic Packaging Products & Materials', "parent_code": '151030', "level_num": '4'},
    '151040': {"name": 'Metals & Mining', "parent_code": '1510', "level_num": '3'},
    '15104010': {"name": 'Aluminum', "parent_code": '151040', "level_num": '4'},
    '15104020': {"name": 'Diversified Metals & Mining', "parent_code": '151040', "level_num": '4'},
    '15104025': {"name": 'Copper', "parent_code": '151040', "level_num": '4'},
    '15104030': {"name": 'Gold', "parent_code": '151040', "level_num": '4'},
    '15104040': {"name": 'Precious Metals & Minerals', "parent_code": '151040', "level_num": '4'},
    '15104045': {"name": 'Silver', "parent_code": '151040', "level_num": '4'},
    '15104050': {"name": 'Steel', "parent_code": '151040', "level_num": '4'},
    '151050': {"name": 'Paper & Forest Products', "parent_code": '1510', "level_num": '3'},
    '15105010': {"name": 'Forest Products', "parent_code": '151050', "level_num": '4'},
    '15105020': {"name": 'Paper Products', "parent_code": '151050', "level_num": '4'},
    '20': {"name": 'Industrials', "parent_code": '', "level_num": '1'},
    '2010': {"name": 'Capital Goods', "parent_code": '20', "level_num": '2'},
    '201010': {"name": 'Aerospace & Defense', "parent_code": '2010', "level_num": '3'},
    '20101010': {"name": 'Aerospace & Defense', "parent_code": '201010', "level_num": '4'},
    '201020': {"name": 'Building Products', "parent_code": '2010', "level_num": '3'},
    '20102010': {"name": 'Building Products', "parent_code": '201020', "level_num": '4'},
    '201030': {"name": 'Construction & Engineering', "parent_code": '2010', "level_num": '3'},
    '20103010': {"name": 'Construction & Engineering', "parent_code": '201030', "level_num": '4'},
    '201040': {"name": 'Electrical Equipment', "parent_code": '2010', "level_num": '3'},
    '20104010': {"name": 'Electrical Components & Equipment', "parent_code": '201040', "level_num": '4'},
    '20104020': {"name": 'Heavy Electrical Equipment', "parent_code": '201040', "level_num": '4'},
    '201050': {"name": 'Industrial Conglomerates', "parent_code": '2010', "level_num": '3'},
    '20105010': {"name": 'Industrial Conglomerates', "parent_code": '201050', "level_num": '4'},
    '201060': {"name": 'Machinery', "parent_code": '2010', "level_num": '3'},
    '20106010': {"name": 'Construction Machinery & Heavy Transportation Equipment', "parent_code": '201060', "level_num": '4'},
    '20106015': {"name": 'Agricultural & Farm Machinery', "parent_code": '201060', "level_num": '4'},
    '20106020': {"name": 'Industrial Machinery & Supplies & Components', "parent_code": '201060', "level_num": '4'},
    '201070': {"name": 'Trading Companies & Distributors', "parent_code": '2010', "level_num": '3'},
    '20107010': {"name": 'Trading Companies & Distributors', "parent_code": '201070', "level_num": '4'},
    '2020': {"name": 'Commercial & Professional Services', "parent_code": '20', "level_num": '2'},
    '202010': {"name": 'Commercial Services & Supplies', "parent_code": '2020', "level_num": '3'},
    '20201010': {"name": 'Commercial Printing', "parent_code": '202010', "level_num": '4'},
    '20201050': {"name": 'Environmental & Facilities Services', "parent_code": '202010', "level_num": '4'},
    '20201060': {"name": 'Office Services & Supplies', "parent_code": '202010', "level_num": '4'},
    '20201070': {"name": 'Diversified Support Services', "parent_code": '202010', "level_num": '4'},
    '20201080': {"name": 'Security & Alarm Services', "parent_code": '202010', "level_num": '4'},
    '202020': {"name": 'Professional Services', "parent_code": '2020', "level_num": '3'},
    '20202010': {"name": 'Human Resource & Employment Services', "parent_code": '202020', "level_num": '4'},
    '20202020': {"name": 'Research & Consulting Services', "parent_code": '202020', "level_num": '4'},
    '20202030': {"name": 'Data Processing & Outsourced Services', "parent_code": '202020', "level_num": '4'},
    '2030': {"name": 'Transportation', "parent_code": '20', "level_num": '2'},
    '203010': {"name": 'Air Freight & Logistics', "parent_code": '2030', "level_num": '3'},
    '20301010': {"name": 'Air Freight & Logistics', "parent_code": '203010', "level_num": '4'},
    '203020': {"name": 'Passenger Airlines', "parent_code": '2030', "level_num": '3'},
    '20302010': {"name": 'Passenger Airlines', "parent_code": '203020', "level_num": '4'},
    '203030': {"name": 'Marine Transportation', "parent_code": '2030', "level_num": '3'},
    '20303010': {"name": 'Marine Transportation', "parent_code": '203030', "level_num": '4'},
    '203040': {"name": 'Ground Transportation', "parent_code": '2030', "level_num": '3'},
    '20304010': {"name": 'Rail Transportation', "parent_code": '203040', "level_num": '4'},
    '20304030': {"name": 'Cargo Ground Transportation', "parent_code": '203040', "level_num": '4'},
    '20304040': {"name": 'Passenger Ground Transportation', "parent_code": '203040', "level_num": '4'},
    '203050': {"name": 'Transportation Infrastructure', "parent_code": '2030', "level_num": '3'},
    '20305010': {"name": 'Airport Services', "parent_code": '203050', "level_num": '4'},
    '20305020': {"name": 'Highways & Railtracks', "parent_code": '203050', "level_num": '4'},
    '20305030': {"name": 'Marine Ports & Services', "parent_code": '203050', "level_num": '4'},
    '25': {"name": 'Consumer Discretionary', "parent_code": '', "level_num": '1'},
    '2510': {"name": 'Automobiles & Components', "parent_code": '25', "level_num": '2'},
    '251010': {"name": 'Automobile Components', "parent_code": '2510', "level_num": '3'},
    '25101010': {"name": 'Automotive Parts & Equipment', "parent_code": '251010', "level_num": '4'},
    '25101020': {"name": 'Tires & Rubber', "parent_code": '251010', "level_num": '4'},
    '251020': {"name": 'Automobiles', "parent_code": '2510', "level_num": '3'},
    '25102010': {"name": 'Automobile Manufacturers', "parent_code": '251020', "level_num": '4'},
    '25102020': {"name": 'Motorcycle Manufacturers', "parent_code": '251020', "level_num": '4'},
    '2520': {"name": 'Consumer Durables & Apparel', "parent_code": '25', "level_num": '2'},
    '252010': {"name": 'Household Durables', "parent_code": '2520', "level_num": '3'},
    '25201010': {"name": 'Consumer Electronics', "parent_code": '252010', "level_num": '4'},
    '25201020': {"name": 'Home Furnishings', "parent_code": '252010', "level_num": '4'},
    '25201030': {"name": 'Homebuilding', "parent_code": '252010', "level_num": '4'},
    '25201040': {"name": 'Household Appliances', "parent_code": '252010', "level_num": '4'},
    '25201050': {"name": 'Housewares & Specialties', "parent_code": '252010', "level_num": '4'},
    '252020': {"name": 'Leisure Products', "parent_code": '2520', "level_num": '3'},
    '25202010': {"name": 'Leisure Products', "parent_code": '252020', "level_num": '4'},
    '252030': {"name": 'Textiles, Apparel & Luxury Goods', "parent_code": '2520', "level_num": '3'},
    '25203010': {"name": 'Apparel, Accessories & Luxury Goods', "parent_code": '252030', "level_num": '4'},
    '25203020': {"name": 'Footwear', "parent_code": '252030', "level_num": '4'},
    '25203030': {"name": 'Textiles', "parent_code": '252030', "level_num": '4'},
    '2530': {"name": 'Consumer Services', "parent_code": '25', "level_num": '2'},
    '253010': {"name": 'Hotels, Restaurants & Leisure', "parent_code": '2530', "level_num": '3'},
    '25301010': {"name": 'Casinos & Gaming', "parent_code": '253010', "level_num": '4'},
    '25301020': {"name": 'Hotels, Resorts & Cruise Lines', "parent_code": '253010', "level_num": '4'},
    '25301030': {"name": 'Leisure Facilities', "parent_code": '253010', "level_num": '4'},
    '25301040': {"name": 'Restaurants', "parent_code": '253010', "level_num": '4'},
    '253020': {"name": 'Diversified Consumer Services', "parent_code": '2530', "level_num": '3'},
    '25302010': {"name": 'Education Services', "parent_code": '253020', "level_num": '4'},
    '25302020': {"name": 'Specialized Consumer Services', "parent_code": '253020', "level_num": '4'},
    '2550': {"name": 'Consumer Discretionary Distribution & Retail', "parent_code": '25', "level_num": '2'},
    '255010': {"name": 'Distributors', "parent_code": '2550', "level_num": '3'},
    '25501010': {"name": 'Distributors', "parent_code": '255010', "level_num": '4'},
    '255030': {"name": 'Broadline Retail', "parent_code": '2550', "level_num": '3'},
    '25503030': {"name": 'Broadline Retail', "parent_code": '255030', "level_num": '4'},
    '255040': {"name": 'Specialty Retail', "parent_code": '2550', "level_num": '3'},
    '25504010': {"name": 'Apparel Retail', "parent_code": '255040', "level_num": '4'},
    '25504020': {"name": 'Computer & Electronics Retail', "parent_code": '255040', "level_num": '4'},
    '25504030': {"name": 'Home Improvement Retail', "parent_code": '255040', "level_num": '4'},
    '25504040': {"name": 'Other Specialty Retail', "parent_code": '255040', "level_num": '4'},
    '25504050': {"name": 'Automotive Retail', "parent_code": '255040', "level_num": '4'},
    '25504060': {"name": 'Homefurnishing Retail', "parent_code": '255040', "level_num": '4'},
    '30': {"name": 'Consumer Staples', "parent_code": '', "level_num": '1'},
    '3010': {"name": 'Consumer Staples Distribution & Retail', "parent_code": '30', "level_num": '2'},
    '301010': {"name": 'Consumer Staples Distribution & Retail', "parent_code": '3010', "level_num": '3'},
    '30101010': {"name": 'Drug Retail', "parent_code": '301010', "level_num": '4'},
    '30101020': {"name": 'Food Distributors', "parent_code": '301010', "level_num": '4'},
    '30101030': {"name": 'Food Retail', "parent_code": '301010', "level_num": '4'},
    '30101040': {"name": 'Consumer Staples Merchandise Retail', "parent_code": '301010', "level_num": '4'},
    '3020': {"name": 'Food, Beverage & Tobacco', "parent_code": '30', "level_num": '2'},
    '302010': {"name": 'Beverages', "parent_code": '3020', "level_num": '3'},
    '30201010': {"name": 'Brewers', "parent_code": '302010', "level_num": '4'},
    '30201020': {"name": 'Distillers & Vintners', "parent_code": '302010', "level_num": '4'},
    '30201030': {"name": 'Soft Drinks & Non-alcoholic Beverages', "parent_code": '302010', "level_num": '4'},
    '302020': {"name": 'Food Products', "parent_code": '3020', "level_num": '3'},
    '30202010': {"name": 'Agricultural Products & Services', "parent_code": '302020', "level_num": '4'},
    '30202030': {"name": 'Packaged Foods & Meats', "parent_code": '302020', "level_num": '4'},
    '302030': {"name": 'Tobacco', "parent_code": '3020', "level_num": '3'},
    '30203010': {"name": 'Tobacco', "parent_code": '302030', "level_num": '4'},
    '3030': {"name": 'Household & Personal Products', "parent_code": '30', "level_num": '2'},
    '303010': {"name": 'Household Products', "parent_code": '3030', "level_num": '3'},
    '30301010': {"name": 'Household Products', "parent_code": '303010', "level_num": '4'},
    '303020': {"name": 'Personal Care Products', "parent_code": '3030', "level_num": '3'},
    '30302010': {"name": 'Personal Care Products', "parent_code": '303020', "level_num": '4'},
    '35': {"name": 'Health Care', "parent_code": '', "level_num": '1'},
    '3510': {"name": 'Health Care Equipment & Services', "parent_code": '35', "level_num": '2'},
    '351010': {"name": 'Health Care Equipment & Supplies', "parent_code": '3510', "level_num": '3'},
    '35101010': {"name": 'Health Care Equipment', "parent_code": '351010', "level_num": '4'},
    '35101020': {"name": 'Health Care Supplies', "parent_code": '351010', "level_num": '4'},
    '351020': {"name": 'Health Care Providers & Services', "parent_code": '3510', "level_num": '3'},
    '35102010': {"name": 'Health Care Distributors', "parent_code": '351020', "level_num": '4'},
    '35102015': {"name": 'Health Care Services', "parent_code": '351020', "level_num": '4'},
    '35102020': {"name": 'Health Care Facilities', "parent_code": '351020', "level_num": '4'},
    '35102030': {"name": 'Managed Health Care', "parent_code": '351020', "level_num": '4'},
    '351030': {"name": 'Health Care Technology', "parent_code": '3510', "level_num": '3'},
    '35103010': {"name": 'Health Care Technology', "parent_code": '351030', "level_num": '4'},
    '3520': {"name": 'Pharmaceuticals, Biotechnology & Life Sciences', "parent_code": '35', "level_num": '2'},
    '352010': {"name": 'Biotechnology', "parent_code": '3520', "level_num": '3'},
    '35201010': {"name": 'Biotechnology', "parent_code": '352010', "level_num": '4'},
    '352020': {"name": 'Pharmaceuticals', "parent_code": '3520', "level_num": '3'},
    '35202010': {"name": 'Pharmaceuticals', "parent_code": '352020', "level_num": '4'},
    '352030': {"name": 'Life Sciences Tools & Services', "parent_code": '3520', "level_num": '3'},
    '35203010': {"name": 'Life Sciences Tools & Services', "parent_code": '352030', "level_num": '4'},
    '40': {"name": 'Financials', "parent_code": '', "level_num": '1'},
    '4010': {"name": 'Banks', "parent_code": '40', "level_num": '2'},
    '401010': {"name": 'Banks', "parent_code": '4010', "level_num": '3'},
    '40101010': {"name": 'Diversified Banks', "parent_code": '401010', "level_num": '4'},
    '40101015': {"name": 'Regional Banks', "parent_code": '401010', "level_num": '4'},
    '4020': {"name": 'Financial Services', "parent_code": '40', "level_num": '2'},
    '402010': {"name": 'Financial Services', "parent_code": '4020', "level_num": '3'},
    '40201020': {"name": 'Diversified Financial Services', "parent_code": '402010', "level_num": '4'},
    '40201030': {"name": 'Multi-Sector Holdings', "parent_code": '402010', "level_num": '4'},
    '40201040': {"name": 'Specialized Finance', "parent_code": '402010', "level_num": '4'},
    '40201050': {"name": 'Commercial & Residential Mortgage Finance', "parent_code": '402010', "level_num": '4'},
    '40201060': {"name": 'Transaction & Payment Processing Services', "parent_code": '402010', "level_num": '4'},
    '402020': {"name": 'Consumer Finance', "parent_code": '4020', "level_num": '3'},
    '40202010': {"name": 'Consumer Finance', "parent_code": '402020', "level_num": '4'},
    '402030': {"name": 'Capital Markets', "parent_code": '4020', "level_num": '3'},
    '40203010': {"name": 'Asset Management & Custody Banks', "parent_code": '402030', "level_num": '4'},
    '40203020': {"name": 'Investment Banking & Brokerage', "parent_code": '402030', "level_num": '4'},
    '40203030': {"name": 'Diversified Capital Markets', "parent_code": '402030', "level_num": '4'},
    '40203040': {"name": 'Financial Exchanges & Data', "parent_code": '402030', "level_num": '4'},
    '402040': {"name": 'Mortgage Real Estate Investment Trusts (REITs)', "parent_code": '4020', "level_num": '3'},
    '40204010': {"name": 'Mortgage REITs', "parent_code": '402040', "level_num": '4'},
    '4030': {"name": 'Insurance', "parent_code": '40', "level_num": '2'},
    '403010': {"name": 'Insurance', "parent_code": '4030', "level_num": '3'},
    '40301010': {"name": 'Insurance Brokers', "parent_code": '403010', "level_num": '4'},
    '40301020': {"name": 'Life & Health Insurance', "parent_code": '403010', "level_num": '4'},
    '40301030': {"name": 'Multi-line Insurance', "parent_code": '403010', "level_num": '4'},
    '40301040': {"name": 'Property & Casualty Insurance', "parent_code": '403010', "level_num": '4'},
    '40301050': {"name": 'Reinsurance', "parent_code": '403010', "level_num": '4'},
    '45': {"name": 'Information Technology', "parent_code": '', "level_num": '1'},
    '4510': {"name": 'Software & Services', "parent_code": '45', "level_num": '2'},
    '451020': {"name": 'IT Services', "parent_code": '4510', "level_num": '3'},
    '45102010': {"name": 'IT Consulting & Other Services', "parent_code": '451020', "level_num": '4'},
    '45102030': {"name": 'Internet Services & Infrastructure', "parent_code": '451020', "level_num": '4'},
    '451030': {"name": 'Software', "parent_code": '4510', "level_num": '3'},
    '45103010': {"name": 'Application Software', "parent_code": '451030', "level_num": '4'},
    '45103020': {"name": 'Systems Software', "parent_code": '451030', "level_num": '4'},
    '4520': {"name": 'Technology Hardware & Equipment', "parent_code": '45', "level_num": '2'},
    '452010': {"name": 'Communications Equipment', "parent_code": '4520', "level_num": '3'},
    '45201020': {"name": 'Communications Equipment', "parent_code": '452010', "level_num": '4'},
    '452020': {"name": 'Technology Hardware, Storage & Peripherals', "parent_code": '4520', "level_num": '3'},
    '45202030': {"name": 'Technology Hardware, Storage & Peripherals', "parent_code": '452020', "level_num": '4'},
    '452030': {"name": 'Electronic Equipment, Instruments & Components', "parent_code": '4520', "level_num": '3'},
    '45203010': {"name": 'Electronic Equipment & Instruments', "parent_code": '452030', "level_num": '4'},
    '45203015': {"name": 'Electronic Components', "parent_code": '452030', "level_num": '4'},
    '45203020': {"name": 'Electronic Manufacturing Services', "parent_code": '452030', "level_num": '4'},
    '45203030': {"name": 'Technology Distributors', "parent_code": '452030', "level_num": '4'},
    '4530': {"name": 'Semiconductors & Semiconductor Equipment', "parent_code": '45', "level_num": '2'},
    '453010': {"name": 'Semiconductors & Semiconductor Equipment', "parent_code": '4530', "level_num": '3'},
    '45301010': {"name": 'Semiconductor Materials & Equipment', "parent_code": '453010', "level_num": '4'},
    '45301020': {"name": 'Semiconductors', "parent_code": '453010', "level_num": '4'},
    '50': {"name": 'Communication Services', "parent_code": '', "level_num": '1'},
    '5010': {"name": 'Telecommunication Services', "parent_code": '50', "level_num": '2'},
    '501010': {"name": 'Diversified Telecommunication Services', "parent_code": '5010', "level_num": '3'},
    '50101010': {"name": 'Alternative Carriers', "parent_code": '501010', "level_num": '4'},
    '50101020': {"name": 'Integrated Telecommunication Services', "parent_code": '501010', "level_num": '4'},
    '501020': {"name": 'Wireless Telecommunication Services', "parent_code": '5010', "level_num": '3'},
    '50102010': {"name": 'Wireless Telecommunication Services', "parent_code": '501020', "level_num": '4'},
    '5020': {"name": 'Media & Entertainment', "parent_code": '50', "level_num": '2'},
    '502010': {"name": 'Media', "parent_code": '5020', "level_num": '3'},
    '50201010': {"name": 'Advertising', "parent_code": '502010', "level_num": '4'},
    '50201020': {"name": 'Broadcasting', "parent_code": '502010', "level_num": '4'},
    '50201030': {"name": 'Cable & Satellite', "parent_code": '502010', "level_num": '4'},
    '50201040': {"name": 'Publishing', "parent_code": '502010', "level_num": '4'},
    '502020': {"name": 'Entertainment', "parent_code": '5020', "level_num": '3'},
    '50202010': {"name": 'Movies & Entertainment', "parent_code": '502020', "level_num": '4'},
    '50202020': {"name": 'Interactive Home Entertainment', "parent_code": '502020', "level_num": '4'},
    '502030': {"name": 'Interactive Media & Services', "parent_code": '5020', "level_num": '3'},
    '50203010': {"name": 'Interactive Media & Services', "parent_code": '502030', "level_num": '4'},
    '55': {"name": 'Utilities', "parent_code": '', "level_num": '1'},
    '5510': {"name": 'Utilities', "parent_code": '55', "level_num": '2'},
    '551010': {"name": 'Electric Utilities', "parent_code": '5510', "level_num": '3'},
    '55101010': {"name": 'Electric Utilities', "parent_code": '551010', "level_num": '4'},
    '551020': {"name": 'Gas Utilities', "parent_code": '5510', "level_num": '3'},
    '55102010': {"name": 'Gas Utilities', "parent_code": '551020', "level_num": '4'},
    '551030': {"name": 'Multi-Utilities', "parent_code": '5510', "level_num": '3'},
    '55103010': {"name": 'Multi-Utilities', "parent_code": '551030', "level_num": '4'},
    '551040': {"name": 'Water Utilities', "parent_code": '5510', "level_num": '3'},
    '55104010': {"name": 'Water Utilities', "parent_code": '551040', "level_num": '4'},
    '551050': {"name": 'Independent Power and Renewable Electricity Producers', "parent_code": '5510', "level_num": '3'},
    '55105010': {"name": 'Independent Power Producers & Energy Traders', "parent_code": '551050', "level_num": '4'},
    '55105020': {"name": 'Renewable Electricity', "parent_code": '551050', "level_num": '4'},
    '60': {"name": 'Real Estate', "parent_code": '', "level_num": '1'},
    '6010': {"name": 'Equity Real Estate Investment Trusts (REITs)', "parent_code": '60', "level_num": '2'},
    '601010': {"name": 'Diversified REITs', "parent_code": '6010', "level_num": '3'},
    '60101010': {"name": 'Diversified REITs', "parent_code": '601010', "level_num": '4'},
    '601025': {"name": 'Industrial REITs', "parent_code": '6010', "level_num": '3'},
    '60102510': {"name": 'Industrial REITs', "parent_code": '601025', "level_num": '4'},
    '601030': {"name": 'Hotel & Resort REITs', "parent_code": '6010', "level_num": '3'},
    '60103010': {"name": 'Hotel & Resort REITs', "parent_code": '601030', "level_num": '4'},
    '601040': {"name": 'Office REITs', "parent_code": '6010', "level_num": '3'},
    '60104010': {"name": 'Office REITs', "parent_code": '601040', "level_num": '4'},
    '601050': {"name": 'Health Care REITs', "parent_code": '6010', "level_num": '3'},
    '60105010': {"name": 'Health Care REITs', "parent_code": '601050', "level_num": '4'},
    '601060': {"name": 'Residential REITs', "parent_code": '6010', "level_num": '3'},
    '60106010': {"name": 'Multi-Family Residential REITs', "parent_code": '601060', "level_num": '4'},
    '60106020': {"name": 'Single-Family Residential REITs', "parent_code": '601060', "level_num": '4'},
    '601070': {"name": 'Retail REITs', "parent_code": '6010', "level_num": '3'},
    '60107010': {"name": 'Retail REITs', "parent_code": '601070', "level_num": '4'},
    '601080': {"name": 'Specialized REITs', "parent_code": '6010', "level_num": '3'},
    '60108010': {"name": 'Other Specialized REITs', "parent_code": '601080', "level_num": '4'},
    '60108020': {"name": 'Self-Storage REITs', "parent_code": '601080', "level_num": '4'},
    '60108030': {"name": 'Telecom Tower REITs', "parent_code": '601080', "level_num": '4'},
    '60108040': {"name": 'Timber REITs', "parent_code": '601080', "level_num": '4'},
    '60108050': {"name": 'Data Center REITs', "parent_code": '601080', "level_num": '4'},
    '6020': {"name": 'Real Estate Management & Development', "parent_code": '60', "level_num": '2'},
    '602010': {"name": 'Real Estate Management & Development', "parent_code": '6020', "level_num": '3'},
    '60201010': {"name": 'Diversified Real Estate Activities', "parent_code": '602010', "level_num": '4'},
    '60201020': {"name": 'Real Estate Operating Companies', "parent_code": '602010', "level_num": '4'},
    '60201030': {"name": 'Real Estate Development', "parent_code": '602010', "level_num": '4'},
    '60201040': {"name": 'Real Estate Services', "parent_code": '602010', "level_num": '4'},
}

# ~503-row static S&P 500 constituents snapshot (dash-form symbols), used
# only when the live GitHub fetch fails. Mirrors _SP500_TICKERS precedent.
_GICS_CONSTITUENTS_STATIC: list[dict[str, str]] = [
    {"symbol": 'MMM', "security": '3M', "sector": 'Industrials', "sub_industry": 'Industrial Conglomerates'},
    {"symbol": 'AOS', "security": 'A. O. Smith', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'ABT', "security": 'Abbott Laboratories', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'ABBV', "security": 'AbbVie', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'ACN', "security": 'Accenture', "sector": 'Information Technology', "sub_industry": 'IT Consulting & Other Services'},
    {"symbol": 'ADBE', "security": 'Adobe Inc.', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'AMD', "security": 'Advanced Micro Devices', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'AES', "security": 'AES Corporation', "sector": 'Utilities', "sub_industry": 'Independent Power Producers & Energy Traders'},
    {"symbol": 'AFL', "security": 'Aflac', "sector": 'Financials', "sub_industry": 'Life & Health Insurance'},
    {"symbol": 'A', "security": 'Agilent Technologies', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'APD', "security": 'Air Products', "sector": 'Materials', "sub_industry": 'Industrial Gases'},
    {"symbol": 'ABNB', "security": 'Airbnb', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'AKAM', "security": 'Akamai Technologies', "sector": 'Information Technology', "sub_industry": 'Internet Services & Infrastructure'},
    {"symbol": 'ALB', "security": 'Albemarle Corporation', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'ARE', "security": 'Alexandria Real Estate Equities', "sector": 'Real Estate', "sub_industry": 'Office REITs'},
    {"symbol": 'ALGN', "security": 'Align Technology', "sector": 'Health Care', "sub_industry": 'Health Care Supplies'},
    {"symbol": 'ALLE', "security": 'Allegion', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'LNT', "security": 'Alliant Energy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'ALL', "security": 'Allstate', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'GOOGL', "security": 'Alphabet Inc. (Class A)', "sector": 'Communication Services', "sub_industry": 'Interactive Media & Services'},
    {"symbol": 'GOOG', "security": 'Alphabet Inc. (Class C)', "sector": 'Communication Services', "sub_industry": 'Interactive Media & Services'},
    {"symbol": 'MO', "security": 'Altria', "sector": 'Consumer Staples', "sub_industry": 'Tobacco'},
    {"symbol": 'AMZN', "security": 'Amazon', "sector": 'Consumer Discretionary', "sub_industry": 'Broadline Retail'},
    {"symbol": 'AMCR', "security": 'Amcor', "sector": 'Materials', "sub_industry": 'Paper & Plastic Packaging Products & Materials'},
    {"symbol": 'AEE', "security": 'Ameren', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'AEP', "security": 'American Electric Power', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'AXP', "security": 'American Express', "sector": 'Financials', "sub_industry": 'Consumer Finance'},
    {"symbol": 'AIG', "security": 'American International Group', "sector": 'Financials', "sub_industry": 'Multi-line Insurance'},
    {"symbol": 'AMT', "security": 'American Tower', "sector": 'Real Estate', "sub_industry": 'Telecom Tower REITs'},
    {"symbol": 'AWK', "security": 'American Water Works', "sector": 'Utilities', "sub_industry": 'Water Utilities'},
    {"symbol": 'AMP', "security": 'Ameriprise Financial', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'AME', "security": 'Ametek', "sector": 'Industrials', "sub_industry": 'Electrical Components & Equipment'},
    {"symbol": 'AMGN', "security": 'Amgen', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'APH', "security": 'Amphenol', "sector": 'Information Technology', "sub_industry": 'Electronic Components'},
    {"symbol": 'ADI', "security": 'Analog Devices', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'AON', "security": 'Aon plc', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'APA', "security": 'APA Corporation', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'APO', "security": 'Apollo Global Management', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'AAPL', "security": 'Apple Inc.', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'AMAT', "security": 'Applied Materials', "sector": 'Information Technology', "sub_industry": 'Semiconductor Materials & Equipment'},
    {"symbol": 'APP', "security": 'AppLovin', "sector": 'Communication Services', "sub_industry": 'Advertising'},
    {"symbol": 'APTV', "security": 'Aptiv', "sector": 'Consumer Discretionary', "sub_industry": 'Automotive Parts & Equipment'},
    {"symbol": 'ACGL', "security": 'Arch Capital Group', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'ADM', "security": 'Archer Daniels Midland', "sector": 'Consumer Staples', "sub_industry": 'Agricultural Products & Services'},
    {"symbol": 'ARES', "security": 'Ares Management', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'ANET', "security": 'Arista Networks', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'AJG', "security": 'Arthur J. Gallagher & Co.', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'AIZ', "security": 'Assurant', "sector": 'Financials', "sub_industry": 'Multi-line Insurance'},
    {"symbol": 'T', "security": 'AT&T', "sector": 'Communication Services', "sub_industry": 'Integrated Telecommunication Services'},
    {"symbol": 'ATO', "security": 'Atmos Energy', "sector": 'Utilities', "sub_industry": 'Gas Utilities'},
    {"symbol": 'ADSK', "security": 'Autodesk', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'ADP', "security": 'Automatic Data Processing', "sector": 'Industrials', "sub_industry": 'Human Resource & Employment Services'},
    {"symbol": 'AZO', "security": 'AutoZone', "sector": 'Consumer Discretionary', "sub_industry": 'Automotive Retail'},
    {"symbol": 'AVB', "security": 'AvalonBay Communities', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'AVY', "security": 'Avery Dennison', "sector": 'Materials', "sub_industry": 'Paper & Plastic Packaging Products & Materials'},
    {"symbol": 'AXON', "security": 'Axon Enterprise', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'BKR', "security": 'Baker Hughes', "sector": 'Energy', "sub_industry": 'Oil & Gas Equipment & Services'},
    {"symbol": 'BALL', "security": 'Ball Corporation', "sector": 'Materials', "sub_industry": 'Metal, Glass & Plastic Containers'},
    {"symbol": 'BAC', "security": 'Bank of America', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'BAX', "security": 'Baxter International', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'BDX', "security": 'Becton Dickinson', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'BRK-B', "security": 'Berkshire Hathaway', "sector": 'Financials', "sub_industry": 'Multi-Sector Holdings'},
    {"symbol": 'BBY', "security": 'Best Buy', "sector": 'Consumer Discretionary', "sub_industry": 'Computer & Electronics Retail'},
    {"symbol": 'TECH', "security": 'Bio-Techne', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'BIIB', "security": 'Biogen', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'BLK', "security": 'BlackRock', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'BX', "security": 'Blackstone Inc.', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'XYZ', "security": 'Block, Inc.', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'BNY', "security": 'BNY Mellon', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'BA', "security": 'Boeing', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'BKNG', "security": 'Booking Holdings', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'BSX', "security": 'Boston Scientific', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'BMY', "security": 'Bristol Myers Squibb', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'AVGO', "security": 'Broadcom', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'BR', "security": 'Broadridge Financial Solutions', "sector": 'Industrials', "sub_industry": 'Data Processing & Outsourced Services'},
    {"symbol": 'BRO', "security": 'Brown & Brown', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'BF-B', "security": 'Brown–Forman', "sector": 'Consumer Staples', "sub_industry": 'Distillers & Vintners'},
    {"symbol": 'BLDR', "security": 'Builders FirstSource', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'BG', "security": 'Bunge Global', "sector": 'Consumer Staples', "sub_industry": 'Agricultural Products & Services'},
    {"symbol": 'BXP', "security": 'BXP, Inc.', "sector": 'Real Estate', "sub_industry": 'Office REITs'},
    {"symbol": 'CHRW', "security": 'C.H. Robinson', "sector": 'Industrials', "sub_industry": 'Air Freight & Logistics'},
    {"symbol": 'CDNS', "security": 'Cadence Design Systems', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'CPT', "security": 'Camden Property Trust', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'COF', "security": 'Capital One', "sector": 'Financials', "sub_industry": 'Consumer Finance'},
    {"symbol": 'CAH', "security": 'Cardinal Health', "sector": 'Health Care', "sub_industry": 'Health Care Distributors'},
    {"symbol": 'CCL', "security": 'Carnival Corporation', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'CARR', "security": 'Carrier Global', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'CVNA', "security": 'Carvana', "sector": 'Consumer Discretionary', "sub_industry": 'Automotive Retail'},
    {"symbol": 'CASY', "security": "Casey's", "sector": 'Consumer Staples', "sub_industry": 'Food Retail'},
    {"symbol": 'CAT', "security": 'Caterpillar Inc.', "sector": 'Industrials', "sub_industry": 'Construction Machinery & Heavy Transportation Equipment'},
    {"symbol": 'CBOE', "security": 'Cboe Global Markets', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'CBRE', "security": 'CBRE Group', "sector": 'Real Estate', "sub_industry": 'Real Estate Services'},
    {"symbol": 'CDW', "security": 'CDW Corporation', "sector": 'Information Technology', "sub_industry": 'Technology Distributors'},
    {"symbol": 'COR', "security": 'Cencora', "sector": 'Health Care', "sub_industry": 'Health Care Distributors'},
    {"symbol": 'CNC', "security": 'Centene Corporation', "sector": 'Health Care', "sub_industry": 'Managed Health Care'},
    {"symbol": 'CNP', "security": 'CenterPoint Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'CF', "security": 'CF Industries', "sector": 'Materials', "sub_industry": 'Fertilizers & Agricultural Chemicals'},
    {"symbol": 'CRL', "security": 'Charles River Laboratories', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'SCHW', "security": 'Charles Schwab Corporation', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'CHTR', "security": 'Charter Communications', "sector": 'Communication Services', "sub_industry": 'Cable & Satellite'},
    {"symbol": 'CVX', "security": 'Chevron Corporation', "sector": 'Energy', "sub_industry": 'Integrated Oil & Gas'},
    {"symbol": 'CMG', "security": 'Chipotle Mexican Grill', "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'CB', "security": 'Chubb Limited', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'CHD', "security": 'Church & Dwight', "sector": 'Consumer Staples', "sub_industry": 'Household Products'},
    {"symbol": 'CIEN', "security": 'Ciena', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'CI', "security": 'Cigna', "sector": 'Health Care', "sub_industry": 'Health Care Services'},
    {"symbol": 'CINF', "security": 'Cincinnati Financial', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'CTAS', "security": 'Cintas', "sector": 'Industrials', "sub_industry": 'Diversified Support Services'},
    {"symbol": 'CSCO', "security": 'Cisco', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'C', "security": 'Citigroup', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'CFG', "security": 'Citizens Financial Group', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'CLX', "security": 'Clorox', "sector": 'Consumer Staples', "sub_industry": 'Household Products'},
    {"symbol": 'CME', "security": 'CME Group', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'CMS', "security": 'CMS Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'KO', "security": 'Coca-Cola Company (The)', "sector": 'Consumer Staples', "sub_industry": 'Soft Drinks & Non-alcoholic Beverages'},
    {"symbol": 'CTSH', "security": 'Cognizant', "sector": 'Information Technology', "sub_industry": 'IT Consulting & Other Services'},
    {"symbol": 'COHR', "security": 'Coherent Corp.', "sector": 'Information Technology', "sub_industry": 'Electronic Components'},
    {"symbol": 'COIN', "security": 'Coinbase', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'CL', "security": 'Colgate-Palmolive', "sector": 'Consumer Staples', "sub_industry": 'Household Products'},
    {"symbol": 'CMCSA', "security": 'Comcast', "sector": 'Communication Services', "sub_industry": 'Cable & Satellite'},
    {"symbol": 'FIX', "security": 'Comfort Systems USA', "sector": 'Industrials', "sub_industry": 'Construction & Engineering'},
    {"symbol": 'COP', "security": 'ConocoPhillips', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'ED', "security": 'Consolidated Edison', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'STZ', "security": 'Constellation Brands', "sector": 'Consumer Staples', "sub_industry": 'Distillers & Vintners'},
    {"symbol": 'CEG', "security": 'Constellation Energy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'COO', "security": 'Cooper Companies (The)', "sector": 'Health Care', "sub_industry": 'Health Care Supplies'},
    {"symbol": 'CPRT', "security": 'Copart', "sector": 'Industrials', "sub_industry": 'Diversified Support Services'},
    {"symbol": 'GLW', "security": 'Corning Inc.', "sector": 'Information Technology', "sub_industry": 'Electronic Components'},
    {"symbol": 'CPAY', "security": 'Corpay', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'CTVA', "security": 'Corteva', "sector": 'Materials', "sub_industry": 'Fertilizers & Agricultural Chemicals'},
    {"symbol": 'CSGP', "security": 'CoStar Group', "sector": 'Real Estate', "sub_industry": 'Real Estate Services'},
    {"symbol": 'COST', "security": 'Costco', "sector": 'Consumer Staples', "sub_industry": 'Consumer Staples Merchandise Retail'},
    {"symbol": 'CRH', "security": 'CRH plc', "sector": 'Materials', "sub_industry": 'Construction Materials'},
    {"symbol": 'CRWD', "security": 'CrowdStrike', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'CCI', "security": 'Crown Castle', "sector": 'Real Estate', "sub_industry": 'Telecom Tower REITs'},
    {"symbol": 'CSX', "security": 'CSX Corporation', "sector": 'Industrials', "sub_industry": 'Rail Transportation'},
    {"symbol": 'CMI', "security": 'Cummins', "sector": 'Industrials', "sub_industry": 'Construction Machinery & Heavy Transportation Equipment'},
    {"symbol": 'CVS', "security": 'CVS Health', "sector": 'Health Care', "sub_industry": 'Health Care Services'},
    {"symbol": 'DHR', "security": 'Danaher Corporation', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'DRI', "security": 'Darden Restaurants', "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'DDOG', "security": 'Datadog', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'DVA', "security": 'DaVita', "sector": 'Health Care', "sub_industry": 'Health Care Services'},
    {"symbol": 'DECK', "security": 'Deckers Brands', "sector": 'Consumer Discretionary', "sub_industry": 'Footwear'},
    {"symbol": 'DE', "security": 'Deere & Company', "sector": 'Industrials', "sub_industry": 'Agricultural & Farm Machinery'},
    {"symbol": 'DELL', "security": 'Dell Technologies', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'DAL', "security": 'Delta Air Lines', "sector": 'Industrials', "sub_industry": 'Passenger Airlines'},
    {"symbol": 'DVN', "security": 'Devon Energy', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'DXCM', "security": 'Dexcom', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'FANG', "security": 'Diamondback Energy', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'DLR', "security": 'Digital Realty', "sector": 'Real Estate', "sub_industry": 'Data Center REITs'},
    {"symbol": 'DG', "security": 'Dollar General', "sector": 'Consumer Staples', "sub_industry": 'Consumer Staples Merchandise Retail'},
    {"symbol": 'DLTR', "security": 'Dollar Tree', "sector": 'Consumer Staples', "sub_industry": 'Consumer Staples Merchandise Retail'},
    {"symbol": 'D', "security": 'Dominion Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'DPZ', "security": "Domino's", "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'DASH', "security": 'DoorDash', "sector": 'Consumer Discretionary', "sub_industry": 'Specialized Consumer Services'},
    {"symbol": 'DOV', "security": 'Dover Corporation', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'DOW', "security": 'Dow Inc.', "sector": 'Materials', "sub_industry": 'Commodity Chemicals'},
    {"symbol": 'DHI', "security": 'D. R. Horton', "sector": 'Consumer Discretionary', "sub_industry": 'Homebuilding'},
    {"symbol": 'DTE', "security": 'DTE Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'DUK', "security": 'Duke Energy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'DD', "security": 'DuPont', "sector": 'Industrials', "sub_industry": 'Industrial Conglomerates'},
    {"symbol": 'ETN', "security": 'Eaton Corporation', "sector": 'Industrials', "sub_industry": 'Electrical Components & Equipment'},
    {"symbol": 'EBAY', "security": 'eBay Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Broadline Retail'},
    {"symbol": 'ECHO', "security": 'EchoStar', "sector": 'Communication Services', "sub_industry": 'Wireless Telecommunication Services'},
    {"symbol": 'ECL', "security": 'Ecolab', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'EIX', "security": 'Edison International', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'EW', "security": 'Edwards Lifesciences', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'ELV', "security": 'Elevance Health', "sector": 'Health Care', "sub_industry": 'Managed Health Care'},
    {"symbol": 'EME', "security": 'Emcor', "sector": 'Industrials', "sub_industry": 'Construction & Engineering'},
    {"symbol": 'EMR', "security": 'Emerson Electric', "sector": 'Industrials', "sub_industry": 'Electrical Components & Equipment'},
    {"symbol": 'ETR', "security": 'Entergy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'EOG', "security": 'EOG Resources', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'EQT', "security": 'EQT Corporation', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'EFX', "security": 'Equifax', "sector": 'Industrials', "sub_industry": 'Research & Consulting Services'},
    {"symbol": 'EQIX', "security": 'Equinix', "sector": 'Real Estate', "sub_industry": 'Data Center REITs'},
    {"symbol": 'EQR', "security": 'Equity Residential', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'ERIE', "security": 'Erie Indemnity', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'ESS', "security": 'Essex Property Trust', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'EL', "security": 'Estée Lauder Companies (The)', "sector": 'Consumer Staples', "sub_industry": 'Personal Care Products'},
    {"symbol": 'EG', "security": 'Everest Group', "sector": 'Financials', "sub_industry": 'Reinsurance'},
    {"symbol": 'EVRG', "security": 'Evergy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'ES', "security": 'Eversource Energy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'EXC', "security": 'Exelon', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'EXE', "security": 'Expand Energy', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'EXPE', "security": 'Expedia Group', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'EXPD', "security": 'Expeditors International', "sector": 'Industrials', "sub_industry": 'Air Freight & Logistics'},
    {"symbol": 'EXR', "security": 'Extra Space Storage', "sector": 'Real Estate', "sub_industry": 'Self-Storage REITs'},
    {"symbol": 'XOM', "security": 'ExxonMobil', "sector": 'Energy', "sub_industry": 'Integrated Oil & Gas'},
    {"symbol": 'FFIV', "security": 'F5, Inc.', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'FDS', "security": 'FactSet', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'FICO', "security": 'Fair Isaac', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'FAST', "security": 'Fastenal', "sector": 'Industrials', "sub_industry": 'Trading Companies & Distributors'},
    {"symbol": 'FRT', "security": 'Federal Realty Investment Trust', "sector": 'Real Estate', "sub_industry": 'Retail REITs'},
    {"symbol": 'FDX', "security": 'FedEx', "sector": 'Industrials', "sub_industry": 'Air Freight & Logistics'},
    {"symbol": 'FDXF', "security": 'FedEx Freight', "sector": 'Industrials', "sub_industry": 'Cargo Ground Transportation'},
    {"symbol": 'FERG', "security": 'Ferguson Enterprises', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'FIS', "security": 'Fidelity National Information Services', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'FITB', "security": 'Fifth Third Bancorp', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'FSLR', "security": 'First Solar', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'FE', "security": 'FirstEnergy', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'FISV', "security": 'Fiserv', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'FLEX', "security": 'Flex Ltd.', "sector": 'Information Technology', "sub_industry": 'Electronic Manufacturing Services'},
    {"symbol": 'F', "security": 'Ford Motor Company', "sector": 'Consumer Discretionary', "sub_industry": 'Automobile Manufacturers'},
    {"symbol": 'FTNT', "security": 'Fortinet', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'FTV', "security": 'Fortive', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'FOXA', "security": 'Fox Corporation (Class A)', "sector": 'Communication Services', "sub_industry": 'Broadcasting'},
    {"symbol": 'FOX', "security": 'Fox Corporation (Class B)', "sector": 'Communication Services', "sub_industry": 'Broadcasting'},
    {"symbol": 'BEN', "security": 'Franklin Resources', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'FCX', "security": 'Freeport-McMoRan', "sector": 'Materials', "sub_industry": 'Copper'},
    {"symbol": 'GRMN', "security": 'Garmin', "sector": 'Consumer Discretionary', "sub_industry": 'Consumer Electronics'},
    {"symbol": 'IT', "security": 'Gartner', "sector": 'Information Technology', "sub_industry": 'IT Consulting & Other Services'},
    {"symbol": 'GE', "security": 'GE Aerospace', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'GEHC', "security": 'GE HealthCare', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'GEV', "security": 'GE Vernova', "sector": 'Industrials', "sub_industry": 'Heavy Electrical Equipment'},
    {"symbol": 'GEN', "security": 'Gen Digital', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'GNRC', "security": 'Generac', "sector": 'Industrials', "sub_industry": 'Heavy Electrical Equipment'},
    {"symbol": 'GD', "security": 'General Dynamics', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'GIS', "security": 'General Mills', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'GM', "security": 'General Motors', "sector": 'Consumer Discretionary', "sub_industry": 'Automobile Manufacturers'},
    {"symbol": 'GPC', "security": 'Genuine Parts Company', "sector": 'Consumer Discretionary', "sub_industry": 'Distributors'},
    {"symbol": 'GILD', "security": 'Gilead Sciences', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'GPN', "security": 'Global Payments', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'GL', "security": 'Globe Life', "sector": 'Financials', "sub_industry": 'Life & Health Insurance'},
    {"symbol": 'GDDY', "security": 'GoDaddy', "sector": 'Information Technology', "sub_industry": 'Internet Services & Infrastructure'},
    {"symbol": 'GS', "security": 'Goldman Sachs', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'HAL', "security": 'Halliburton', "sector": 'Energy', "sub_industry": 'Oil & Gas Equipment & Services'},
    {"symbol": 'HIG', "security": 'Hartford (The)', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'HAS', "security": 'Hasbro', "sector": 'Consumer Discretionary', "sub_industry": 'Leisure Products'},
    {"symbol": 'HCA', "security": 'HCA Healthcare', "sector": 'Health Care', "sub_industry": 'Health Care Facilities'},
    {"symbol": 'DOC', "security": 'Healthpeak Properties', "sector": 'Real Estate', "sub_industry": 'Health Care REITs'},
    {"symbol": 'HSIC', "security": 'Henry Schein', "sector": 'Health Care', "sub_industry": 'Health Care Distributors'},
    {"symbol": 'HSY', "security": 'Hershey Company (The)', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'HPE', "security": 'Hewlett Packard Enterprise', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'HLT', "security": 'Hilton Worldwide', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'HD', "security": 'Home Depot (The)', "sector": 'Consumer Discretionary', "sub_industry": 'Home Improvement Retail'},
    {"symbol": 'HONA', "security": 'Honeywell Aerospace', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'HON', "security": 'Honeywell Technologies', "sector": 'Industrials', "sub_industry": 'Industrial Conglomerates'},
    {"symbol": 'HRL', "security": 'Hormel Foods', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'HST', "security": 'Host Hotels & Resorts', "sector": 'Real Estate', "sub_industry": 'Hotel & Resort REITs'},
    {"symbol": 'HWM', "security": 'Howmet Aerospace', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'HPQ', "security": 'HP Inc.', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'HUBB', "security": 'Hubbell Incorporated', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'HUM', "security": 'Humana', "sector": 'Health Care', "sub_industry": 'Managed Health Care'},
    {"symbol": 'HBAN', "security": 'Huntington Bancshares', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'HII', "security": 'Huntington Ingalls Industries', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'IBM', "security": 'IBM', "sector": 'Information Technology', "sub_industry": 'IT Consulting & Other Services'},
    {"symbol": 'IEX', "security": 'IDEX Corporation', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'IDXX', "security": 'Idexx Laboratories', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'ITW', "security": 'Illinois Tool Works', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'INCY', "security": 'Incyte', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'IR', "security": 'Ingersoll Rand', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'PODD', "security": 'Insulet Corporation', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'INTC', "security": 'Intel', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'IBKR', "security": 'Interactive Brokers', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'ICE', "security": 'Intercontinental Exchange', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'IFF', "security": 'International Flavors & Fragrances', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'IP', "security": 'International Paper', "sector": 'Materials', "sub_industry": 'Paper & Plastic Packaging Products & Materials'},
    {"symbol": 'INTU', "security": 'Intuit', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'ISRG', "security": 'Intuitive Surgical', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'IVZ', "security": 'Invesco', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'INVH', "security": 'Invitation Homes', "sector": 'Real Estate', "sub_industry": 'Single-Family Residential REITs'},
    {"symbol": 'IQV', "security": 'IQVIA', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'IRM', "security": 'Iron Mountain', "sector": 'Real Estate', "sub_industry": 'Other Specialized REITs'},
    {"symbol": 'JBHT', "security": 'J.B. Hunt', "sector": 'Industrials', "sub_industry": 'Cargo Ground Transportation'},
    {"symbol": 'JBL', "security": 'Jabil', "sector": 'Information Technology', "sub_industry": 'Electronic Manufacturing Services'},
    {"symbol": 'JKHY', "security": 'Jack Henry & Associates', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'J', "security": 'Jacobs Solutions', "sector": 'Industrials', "sub_industry": 'Construction & Engineering'},
    {"symbol": 'JNJ', "security": 'Johnson & Johnson', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'JCI', "security": 'Johnson Controls', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'JPM', "security": 'JPMorgan Chase', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'KVUE', "security": 'Kenvue', "sector": 'Consumer Staples', "sub_industry": 'Personal Care Products'},
    {"symbol": 'KDP', "security": 'Keurig Dr Pepper', "sector": 'Consumer Staples', "sub_industry": 'Soft Drinks & Non-alcoholic Beverages'},
    {"symbol": 'KEY', "security": 'KeyCorp', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'KEYS', "security": 'Keysight Technologies', "sector": 'Information Technology', "sub_industry": 'Electronic Equipment & Instruments'},
    {"symbol": 'KMB', "security": 'Kimberly-Clark', "sector": 'Consumer Staples', "sub_industry": 'Household Products'},
    {"symbol": 'KIM', "security": 'Kimco Realty', "sector": 'Real Estate', "sub_industry": 'Retail REITs'},
    {"symbol": 'KMI', "security": 'Kinder Morgan', "sector": 'Energy', "sub_industry": 'Oil & Gas Storage & Transportation'},
    {"symbol": 'KKR', "security": 'KKR & Co.', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'KLAC', "security": 'KLA Corporation', "sector": 'Information Technology', "sub_industry": 'Semiconductor Materials & Equipment'},
    {"symbol": 'KHC', "security": 'Kraft Heinz', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'KR', "security": 'Kroger', "sector": 'Consumer Staples', "sub_industry": 'Food Retail'},
    {"symbol": 'LHX', "security": 'L3Harris', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'LH', "security": 'Labcorp', "sector": 'Health Care', "sub_industry": 'Health Care Services'},
    {"symbol": 'LRCX', "security": 'Lam Research', "sector": 'Information Technology', "sub_industry": 'Semiconductor Materials & Equipment'},
    {"symbol": 'LVS', "security": 'Las Vegas Sands', "sector": 'Consumer Discretionary', "sub_industry": 'Casinos & Gaming'},
    {"symbol": 'LDOS', "security": 'Leidos', "sector": 'Industrials', "sub_industry": 'Diversified Support Services'},
    {"symbol": 'LEN', "security": 'Lennar', "sector": 'Consumer Discretionary', "sub_industry": 'Homebuilding'},
    {"symbol": 'LII', "security": 'Lennox International', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'LLY', "security": 'Lilly (Eli)', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'LIN', "security": 'Linde plc', "sector": 'Materials', "sub_industry": 'Industrial Gases'},
    {"symbol": 'LYV', "security": 'Live Nation Entertainment', "sector": 'Communication Services', "sub_industry": 'Movies & Entertainment'},
    {"symbol": 'LMT', "security": 'Lockheed Martin', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'L', "security": 'Loews Corporation', "sector": 'Financials', "sub_industry": 'Multi-line Insurance'},
    {"symbol": 'LOW', "security": "Lowe's", "sector": 'Consumer Discretionary', "sub_industry": 'Home Improvement Retail'},
    {"symbol": 'LULU', "security": 'Lululemon Athletica', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel, Accessories & Luxury Goods'},
    {"symbol": 'LITE', "security": 'Lumentum', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'LYB', "security": 'LyondellBasell', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'MTB', "security": 'M&T Bank', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'MPC', "security": 'Marathon Petroleum', "sector": 'Energy', "sub_industry": 'Oil & Gas Refining & Marketing'},
    {"symbol": 'MAR', "security": 'Marriott International', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'MRSH', "security": 'Marsh McLennan', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'MLM', "security": 'Martin Marietta Materials', "sector": 'Materials', "sub_industry": 'Construction Materials'},
    {"symbol": 'MRVL', "security": 'Marvell Technology', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'MAS', "security": 'Masco', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'MA', "security": 'Mastercard', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'MKC', "security": 'McCormick & Company', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'MCD', "security": "McDonald's", "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'MCK', "security": 'McKesson Corporation', "sector": 'Health Care', "sub_industry": 'Health Care Distributors'},
    {"symbol": 'MDT', "security": 'Medtronic', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'MRK', "security": 'Merck & Co.', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'META', "security": 'Meta Platforms', "sector": 'Communication Services', "sub_industry": 'Interactive Media & Services'},
    {"symbol": 'MET', "security": 'MetLife', "sector": 'Financials', "sub_industry": 'Life & Health Insurance'},
    {"symbol": 'MTD', "security": 'Mettler Toledo', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'MGM', "security": 'MGM Resorts', "sector": 'Consumer Discretionary', "sub_industry": 'Casinos & Gaming'},
    {"symbol": 'MCHP', "security": 'Microchip Technology', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'MU', "security": 'Micron Technology', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'MSFT', "security": 'Microsoft', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'MAA', "security": 'Mid-America Apartment Communities', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'MRNA', "security": 'Moderna', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'TAP', "security": 'Molson Coors Beverage Company', "sector": 'Consumer Staples', "sub_industry": 'Brewers'},
    {"symbol": 'MDLZ', "security": 'Mondelez International', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'MPWR', "security": 'Monolithic Power Systems', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'MNST', "security": 'Monster Beverage', "sector": 'Consumer Staples', "sub_industry": 'Soft Drinks & Non-alcoholic Beverages'},
    {"symbol": 'MCO', "security": "Moody's Corporation", "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'MS', "security": 'Morgan Stanley', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'MOS', "security": 'Mosaic Company (The)', "sector": 'Materials', "sub_industry": 'Fertilizers & Agricultural Chemicals'},
    {"symbol": 'MSI', "security": 'Motorola Solutions', "sector": 'Information Technology', "sub_industry": 'Communications Equipment'},
    {"symbol": 'MSCI', "security": 'MSCI', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'NDAQ', "security": 'Nasdaq, Inc.', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'NTAP', "security": 'NetApp', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'NFLX', "security": 'Netflix', "sector": 'Communication Services', "sub_industry": 'Movies & Entertainment'},
    {"symbol": 'NEM', "security": 'Newmont', "sector": 'Materials', "sub_industry": 'Gold'},
    {"symbol": 'NWSA', "security": 'News Corp (Class A)', "sector": 'Communication Services', "sub_industry": 'Publishing'},
    {"symbol": 'NWS', "security": 'News Corp (Class B)', "sector": 'Communication Services', "sub_industry": 'Publishing'},
    {"symbol": 'NEE', "security": 'NextEra Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'NKE', "security": 'Nike, Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel, Accessories & Luxury Goods'},
    {"symbol": 'NI', "security": 'NiSource', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'NDSN', "security": 'Nordson Corporation', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'NSC', "security": 'Norfolk Southern', "sector": 'Industrials', "sub_industry": 'Rail Transportation'},
    {"symbol": 'NTRS', "security": 'Northern Trust', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'NOC', "security": 'Northrop Grumman', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'NCLH', "security": 'Norwegian Cruise Line Holdings', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'NRG', "security": 'NRG Energy', "sector": 'Utilities', "sub_industry": 'Independent Power Producers & Energy Traders'},
    {"symbol": 'NUE', "security": 'Nucor', "sector": 'Materials', "sub_industry": 'Steel'},
    {"symbol": 'NVDA', "security": 'Nvidia', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'NVR', "security": 'NVR, Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Homebuilding'},
    {"symbol": 'NXPI', "security": 'NXP Semiconductors', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'ORLY', "security": "O'Reilly Automotive", "sector": 'Consumer Discretionary', "sub_industry": 'Automotive Retail'},
    {"symbol": 'OXY', "security": 'Occidental Petroleum', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'ODFL', "security": 'Old Dominion', "sector": 'Industrials', "sub_industry": 'Cargo Ground Transportation'},
    {"symbol": 'OMC', "security": 'Omnicom Group', "sector": 'Communication Services', "sub_industry": 'Advertising'},
    {"symbol": 'ON', "security": 'ON Semiconductor', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'OKE', "security": 'Oneok', "sector": 'Energy', "sub_industry": 'Oil & Gas Storage & Transportation'},
    {"symbol": 'ORCL', "security": 'Oracle Corporation', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'OTIS', "security": 'Otis Worldwide', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'PCAR', "security": 'Paccar', "sector": 'Industrials', "sub_industry": 'Construction Machinery & Heavy Transportation Equipment'},
    {"symbol": 'PKG', "security": 'Packaging Corporation of America', "sector": 'Materials', "sub_industry": 'Paper & Plastic Packaging Products & Materials'},
    {"symbol": 'PLTR', "security": 'Palantir Technologies', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'PANW', "security": 'Palo Alto Networks', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'PSKY', "security": 'Paramount Skydance Corporation', "sector": 'Communication Services', "sub_industry": 'Movies & Entertainment'},
    {"symbol": 'PH', "security": 'Parker Hannifin', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'PAYX', "security": 'Paychex', "sector": 'Industrials', "sub_industry": 'Human Resource & Employment Services'},
    {"symbol": 'PYPL', "security": 'PayPal', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'PNR', "security": 'Pentair', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'PEP', "security": 'PepsiCo', "sector": 'Consumer Staples', "sub_industry": 'Soft Drinks & Non-alcoholic Beverages'},
    {"symbol": 'PFE', "security": 'Pfizer', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'PCG', "security": 'PG&E Corporation', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'PM', "security": 'Philip Morris International', "sector": 'Consumer Staples', "sub_industry": 'Tobacco'},
    {"symbol": 'PSX', "security": 'Phillips 66', "sector": 'Energy', "sub_industry": 'Oil & Gas Refining & Marketing'},
    {"symbol": 'PNW', "security": 'Pinnacle West Capital', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'PNC', "security": 'PNC Financial Services', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'PPG', "security": 'PPG Industries', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'PPL', "security": 'PPL Corporation', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'PFG', "security": 'Principal Financial Group', "sector": 'Financials', "sub_industry": 'Life & Health Insurance'},
    {"symbol": 'PG', "security": 'Procter & Gamble', "sector": 'Consumer Staples', "sub_industry": 'Personal Care Products'},
    {"symbol": 'PGR', "security": 'Progressive Corporation', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'PLD', "security": 'Prologis', "sector": 'Real Estate', "sub_industry": 'Industrial REITs'},
    {"symbol": 'PRU', "security": 'Prudential Financial', "sector": 'Financials', "sub_industry": 'Life & Health Insurance'},
    {"symbol": 'PEG', "security": 'Public Service Enterprise Group', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'PTC', "security": 'PTC Inc.', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'PSA', "security": 'Public Storage', "sector": 'Real Estate', "sub_industry": 'Self-Storage REITs'},
    {"symbol": 'PHM', "security": 'PulteGroup', "sector": 'Consumer Discretionary', "sub_industry": 'Homebuilding'},
    {"symbol": 'PWR', "security": 'Quanta Services', "sector": 'Industrials', "sub_industry": 'Construction & Engineering'},
    {"symbol": 'QCOM', "security": 'Qualcomm', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'DGX', "security": 'Quest Diagnostics', "sector": 'Health Care', "sub_industry": 'Health Care Services'},
    {"symbol": 'Q', "security": 'Qnity Electronics', "sector": 'Information Technology', "sub_industry": 'Semiconductor Materials & Equipment'},
    {"symbol": 'RL', "security": 'Ralph Lauren Corporation', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel, Accessories & Luxury Goods'},
    {"symbol": 'RJF', "security": 'Raymond James Financial', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'RTX', "security": 'RTX Corporation', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'O', "security": 'Realty Income', "sector": 'Real Estate', "sub_industry": 'Retail REITs'},
    {"symbol": 'REG', "security": 'Regency Centers', "sector": 'Real Estate', "sub_industry": 'Retail REITs'},
    {"symbol": 'REGN', "security": 'Regeneron Pharmaceuticals', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'RF', "security": 'Regions Financial Corporation', "sector": 'Financials', "sub_industry": 'Regional Banks'},
    {"symbol": 'RSG', "security": 'Republic Services', "sector": 'Industrials', "sub_industry": 'Environmental & Facilities Services'},
    {"symbol": 'RMD', "security": 'ResMed|', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'RVTY', "security": 'Revvity', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'HOOD', "security": 'Robinhood Markets', "sector": 'Financials', "sub_industry": 'Investment Banking & Brokerage'},
    {"symbol": 'ROK', "security": 'Rockwell Automation', "sector": 'Industrials', "sub_industry": 'Electrical Components & Equipment'},
    {"symbol": 'ROL', "security": 'Rollins, Inc.', "sector": 'Industrials', "sub_industry": 'Environmental & Facilities Services'},
    {"symbol": 'ROP', "security": 'Roper Technologies', "sector": 'Information Technology', "sub_industry": 'Electronic Equipment & Instruments'},
    {"symbol": 'ROST', "security": 'Ross Stores', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel Retail'},
    {"symbol": 'RCL', "security": 'Royal Caribbean Group', "sector": 'Consumer Discretionary', "sub_industry": 'Hotels, Resorts & Cruise Lines'},
    {"symbol": 'SPGI', "security": 'S&P Global', "sector": 'Financials', "sub_industry": 'Financial Exchanges & Data'},
    {"symbol": 'CRM', "security": 'Salesforce', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'SNDK', "security": 'Sandisk', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'SBAC', "security": 'SBA Communications', "sector": 'Real Estate', "sub_industry": 'Telecom Tower REITs'},
    {"symbol": 'SLB', "security": 'Schlumberger', "sector": 'Energy', "sub_industry": 'Oil & Gas Equipment & Services'},
    {"symbol": 'STX', "security": 'Seagate Technology', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'SRE', "security": 'Sempra', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'NOW', "security": 'ServiceNow', "sector": 'Information Technology', "sub_industry": 'Systems Software'},
    {"symbol": 'SHW', "security": 'Sherwin-Williams', "sector": 'Materials', "sub_industry": 'Specialty Chemicals'},
    {"symbol": 'SPG', "security": 'Simon Property Group', "sector": 'Real Estate', "sub_industry": 'Retail REITs'},
    {"symbol": 'SWKS', "security": 'Skyworks Solutions', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'SJM', "security": 'J.M. Smucker Company (The)', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'SW', "security": 'Smurfit Westrock', "sector": 'Materials', "sub_industry": 'Paper & Plastic Packaging Products & Materials'},
    {"symbol": 'SNA', "security": 'Snap-on', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'SOLV', "security": 'Solventum', "sector": 'Health Care', "sub_industry": 'Health Care Technology'},
    {"symbol": 'SO', "security": 'Southern Company', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'LUV', "security": 'Southwest Airlines', "sector": 'Industrials', "sub_industry": 'Passenger Airlines'},
    {"symbol": 'SWK', "security": 'Stanley Black & Decker', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'SBUX', "security": 'Starbucks', "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'STT', "security": 'State Street Corporation', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'STLD', "security": 'Steel Dynamics', "sector": 'Materials', "sub_industry": 'Steel'},
    {"symbol": 'STE', "security": 'Steris', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'SYK', "security": 'Stryker Corporation', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'SMCI', "security": 'Supermicro', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'SYF', "security": 'Synchrony Financial', "sector": 'Financials', "sub_industry": 'Consumer Finance'},
    {"symbol": 'SNPS', "security": 'Synopsys', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'SYY', "security": 'Sysco', "sector": 'Consumer Staples', "sub_industry": 'Food Distributors'},
    {"symbol": 'TMUS', "security": 'T-Mobile US', "sector": 'Communication Services', "sub_industry": 'Wireless Telecommunication Services'},
    {"symbol": 'TROW', "security": 'T. Rowe Price', "sector": 'Financials', "sub_industry": 'Asset Management & Custody Banks'},
    {"symbol": 'TTWO', "security": 'Take-Two Interactive', "sector": 'Communication Services', "sub_industry": 'Interactive Home Entertainment'},
    {"symbol": 'TPR', "security": 'Tapestry, Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel, Accessories & Luxury Goods'},
    {"symbol": 'TRGP', "security": 'Targa Resources', "sector": 'Energy', "sub_industry": 'Oil & Gas Storage & Transportation'},
    {"symbol": 'TGT', "security": 'Target Corporation', "sector": 'Consumer Staples', "sub_industry": 'Consumer Staples Merchandise Retail'},
    {"symbol": 'TEL', "security": 'TE Connectivity', "sector": 'Information Technology', "sub_industry": 'Electronic Manufacturing Services'},
    {"symbol": 'TDY', "security": 'Teledyne Technologies', "sector": 'Information Technology', "sub_industry": 'Electronic Equipment & Instruments'},
    {"symbol": 'TER', "security": 'Teradyne', "sector": 'Information Technology', "sub_industry": 'Semiconductor Materials & Equipment'},
    {"symbol": 'TSLA', "security": 'Tesla, Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Automobile Manufacturers'},
    {"symbol": 'TXN', "security": 'Texas Instruments', "sector": 'Information Technology', "sub_industry": 'Semiconductors'},
    {"symbol": 'TPL', "security": 'Texas Pacific Land Corporation', "sector": 'Energy', "sub_industry": 'Oil & Gas Exploration & Production'},
    {"symbol": 'TXT', "security": 'Textron', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'TMO', "security": 'Thermo Fisher Scientific', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'TJX', "security": 'TJX Companies', "sector": 'Consumer Discretionary', "sub_industry": 'Apparel Retail'},
    {"symbol": 'TKO', "security": 'TKO Group Holdings', "sector": 'Communication Services', "sub_industry": 'Movies & Entertainment'},
    {"symbol": 'TTD', "security": 'Trade Desk (The)', "sector": 'Communication Services', "sub_industry": 'Advertising'},
    {"symbol": 'TSCO', "security": 'Tractor Supply', "sector": 'Consumer Discretionary', "sub_industry": 'Other Specialty Retail'},
    {"symbol": 'TT', "security": 'Trane Technologies', "sector": 'Industrials', "sub_industry": 'Building Products'},
    {"symbol": 'TDG', "security": 'TransDigm Group', "sector": 'Industrials', "sub_industry": 'Aerospace & Defense'},
    {"symbol": 'TRV', "security": 'Travelers Companies (The)', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'TRMB', "security": 'Trimble Inc.', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'TFC', "security": 'Truist Financial', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'TYL', "security": 'Tyler Technologies', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'TSN', "security": 'Tyson Foods', "sector": 'Consumer Staples', "sub_industry": 'Packaged Foods & Meats'},
    {"symbol": 'USB', "security": 'U.S. Bancorp', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'UBER', "security": 'Uber', "sector": 'Industrials', "sub_industry": 'Passenger Ground Transportation'},
    {"symbol": 'UDR', "security": 'UDR, Inc.', "sector": 'Real Estate', "sub_industry": 'Multi-Family Residential REITs'},
    {"symbol": 'ULTA', "security": 'Ulta Beauty', "sector": 'Consumer Discretionary', "sub_industry": 'Other Specialty Retail'},
    {"symbol": 'UNP', "security": 'Union Pacific Corporation', "sector": 'Industrials', "sub_industry": 'Rail Transportation'},
    {"symbol": 'UAL', "security": 'United Airlines Holdings', "sector": 'Industrials', "sub_industry": 'Passenger Airlines'},
    {"symbol": 'UPS', "security": 'United Parcel Service', "sector": 'Industrials', "sub_industry": 'Air Freight & Logistics'},
    {"symbol": 'URI', "security": 'United Rentals', "sector": 'Industrials', "sub_industry": 'Trading Companies & Distributors'},
    {"symbol": 'UNH', "security": 'UnitedHealth Group', "sector": 'Health Care', "sub_industry": 'Managed Health Care'},
    {"symbol": 'UHS', "security": 'Universal Health Services', "sector": 'Health Care', "sub_industry": 'Health Care Facilities'},
    {"symbol": 'VLO', "security": 'Valero Energy', "sector": 'Energy', "sub_industry": 'Oil & Gas Refining & Marketing'},
    {"symbol": 'VEEV', "security": 'Veeva Systems', "sector": 'Health Care', "sub_industry": 'Health Care Technology'},
    {"symbol": 'VTR', "security": 'Ventas', "sector": 'Real Estate', "sub_industry": 'Health Care REITs'},
    {"symbol": 'VLTO', "security": 'Veralto', "sector": 'Industrials', "sub_industry": 'Environmental & Facilities Services'},
    {"symbol": 'VRSN', "security": 'Verisign', "sector": 'Information Technology', "sub_industry": 'Internet Services & Infrastructure'},
    {"symbol": 'VRSK', "security": 'Verisk Analytics', "sector": 'Industrials', "sub_industry": 'Research & Consulting Services'},
    {"symbol": 'VZ', "security": 'Verizon', "sector": 'Communication Services', "sub_industry": 'Integrated Telecommunication Services'},
    {"symbol": 'VRTX', "security": 'Vertex Pharmaceuticals', "sector": 'Health Care', "sub_industry": 'Biotechnology'},
    {"symbol": 'VRT', "security": 'Vertiv', "sector": 'Industrials', "sub_industry": 'Electrical Components & Equipment'},
    {"symbol": 'VTRS', "security": 'Viatris', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
    {"symbol": 'VICI', "security": 'Vici Properties', "sector": 'Real Estate', "sub_industry": 'Hotel & Resort REITs'},
    {"symbol": 'V', "security": 'Visa Inc.', "sector": 'Financials', "sub_industry": 'Transaction & Payment Processing Services'},
    {"symbol": 'VST', "security": 'Vistra Corp.', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'VMC', "security": 'Vulcan Materials Company', "sector": 'Materials', "sub_industry": 'Construction Materials'},
    {"symbol": 'WRB', "security": 'W. R. Berkley Corporation', "sector": 'Financials', "sub_industry": 'Property & Casualty Insurance'},
    {"symbol": 'GWW', "security": 'W. W. Grainger', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'WAB', "security": 'Wabtec', "sector": 'Industrials', "sub_industry": 'Construction Machinery & Heavy Transportation Equipment'},
    {"symbol": 'WMT', "security": 'Walmart', "sector": 'Consumer Staples', "sub_industry": 'Consumer Staples Merchandise Retail'},
    {"symbol": 'DIS', "security": 'Walt Disney Company (The)', "sector": 'Communication Services', "sub_industry": 'Movies & Entertainment'},
    {"symbol": 'WBD', "security": 'Warner Bros. Discovery', "sector": 'Communication Services', "sub_industry": 'Broadcasting'},
    {"symbol": 'WM', "security": 'Waste Management', "sector": 'Industrials', "sub_industry": 'Environmental & Facilities Services'},
    {"symbol": 'WAT', "security": 'Waters Corporation', "sector": 'Health Care', "sub_industry": 'Life Sciences Tools & Services'},
    {"symbol": 'WEC', "security": 'WEC Energy Group', "sector": 'Utilities', "sub_industry": 'Electric Utilities'},
    {"symbol": 'WFC', "security": 'Wells Fargo', "sector": 'Financials', "sub_industry": 'Diversified Banks'},
    {"symbol": 'WELL', "security": 'Welltower', "sector": 'Real Estate', "sub_industry": 'Health Care REITs'},
    {"symbol": 'WST', "security": 'West Pharmaceutical Services', "sector": 'Health Care', "sub_industry": 'Health Care Supplies'},
    {"symbol": 'WDC', "security": 'Western Digital', "sector": 'Information Technology', "sub_industry": 'Technology Hardware, Storage & Peripherals'},
    {"symbol": 'WY', "security": 'Weyerhaeuser', "sector": 'Real Estate', "sub_industry": 'Timber REITs'},
    {"symbol": 'WSM', "security": 'Williams-Sonoma, Inc.', "sector": 'Consumer Discretionary', "sub_industry": 'Homefurnishing Retail'},
    {"symbol": 'WMB', "security": 'Williams Companies', "sector": 'Energy', "sub_industry": 'Oil & Gas Storage & Transportation'},
    {"symbol": 'WTW', "security": 'Willis Towers Watson', "sector": 'Financials', "sub_industry": 'Insurance Brokers'},
    {"symbol": 'WDAY', "security": 'Workday, Inc.', "sector": 'Information Technology', "sub_industry": 'Application Software'},
    {"symbol": 'WYNN', "security": 'Wynn Resorts', "sector": 'Consumer Discretionary', "sub_industry": 'Casinos & Gaming'},
    {"symbol": 'XEL', "security": 'Xcel Energy', "sector": 'Utilities', "sub_industry": 'Multi-Utilities'},
    {"symbol": 'XYL', "security": 'Xylem Inc.', "sector": 'Industrials', "sub_industry": 'Industrial Machinery & Supplies & Components'},
    {"symbol": 'YUM', "security": 'Yum! Brands', "sector": 'Consumer Discretionary', "sub_industry": 'Restaurants'},
    {"symbol": 'ZBRA', "security": 'Zebra Technologies', "sector": 'Information Technology', "sub_industry": 'Electronic Equipment & Instruments'},
    {"symbol": 'ZBH', "security": 'Zimmer Biomet', "sector": 'Health Care', "sub_industry": 'Health Care Equipment'},
    {"symbol": 'ZTS', "security": 'Zoetis', "sector": 'Health Care', "sub_industry": 'Pharmaceuticals'},
]

# ---------------------------------------------------------------------------
# GICS classification accessor
# ---------------------------------------------------------------------------

_GICS_CONSTITUENTS_URL = (
    "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/"
    "main/data/constituents.csv"
)

_gics_cache: list[dict[str, str]] | None = None


def _fetch_constituents() -> list[dict[str, str]]:
    """Fetch live constituents.csv; on any failure return the static snapshot."""
    try:
        import pandas as pd

        df = pd.read_csv(_GICS_CONSTITUENTS_URL)
        rows = []
        for _, row in df.iterrows():
            rows.append({
                "symbol": str(row["Symbol"]).replace(".", "-"),
                "security": str(row["Security"]),
                "sector": str(row["GICS Sector"]),
                "sub_industry": str(row["GICS Sub-Industry"]),
            })
        return rows
    except Exception as exc:  # noqa: BLE001 — mirror get_sp500's blanket fallback
        import logging

        logging.getLogger(__name__).warning(
            "GICS constituents fetch failed (%s); using static snapshot",
            exc,
        )
        return list(_GICS_CONSTITUENTS_STATIC)


def _sub_industry_code_index() -> dict[str, str]:
    """name -> code for LEVEL-4 rows only (names collide across tiers)."""
    idx = {}
    for code, r in _GICS_HIERARCHY.items():
        if r["level_num"] == "4":
            idx.setdefault(r["name"], code)
    return idx


def _rollup(sub_code: str) -> dict[str, str]:
    """Walk parent chain: sub-industry -> industry -> group -> sector."""
    sub = _GICS_HIERARCHY[sub_code]
    ind = _GICS_HIERARCHY[sub["parent_code"]]
    grp = _GICS_HIERARCHY[ind["parent_code"]]
    sec = _GICS_HIERARCHY[grp["parent_code"]]
    return {
        "industry_group": grp["name"],
        "industry": ind["name"],
        "sector": sec["name"],
    }


def _resolve_symbol(bare: str, prefix_map: dict[str, str]) -> str:
    """Prefer an exchange-prefixed match (tolerant of . vs -); else bare."""
    if bare in prefix_map:
        return prefix_map[bare]
    for key, val in prefix_map.items():
        if key.replace("-", ".") == bare.replace("-", "."):
            return val
    return bare


def get_gics_classifications(
    *,
    force_refetch: bool = False,
    symbol_map: dict[str, str] | None = None,
) -> list[dict[str, str]]:
    """S&P 500 member GICS classification with four-tier roll-up.

    Parameters
    ----------
    force_refetch : bool
        Bypass the in-memory cache and refetch constituents.csv.
    symbol_map : dict[str, str] | None
        Mapping ``bare_symbol -> exchange_prefixed_symbol`` (e.g.
        ``{"AAPL": "NASDAQ:AAPL", "BRK-B": "NYSE:BRK.B"}``), used to emit
        ``symbol`` in the same form ``ohlcv`` stores.  Unmatched symbols keep
        bare dash-form.
    """
    global _gics_cache
    if _gics_cache is not None and not force_refetch:
        rows = _gics_cache
    else:
        constituents = _fetch_constituents()
        idx = _sub_industry_code_index()
        rows = []
        for c in constituents:
            sub_code = idx.get(c["sub_industry"])
            if sub_code is None:
                raise ValueError(
                    f"Unknown GICS sub-industry: {c['sub_industry']!r} "
                    f"({c['symbol']})"
                )
            rows.append({
                "symbol": c["symbol"],
                "security": c["security"],
                "sub_industry": c["sub_industry"],
                **_rollup(sub_code),
            })
        _gics_cache = rows

    prefix_map = symbol_map or {}
    out = []
    for r in rows:
        row = dict(r)
        row["symbol"] = _resolve_symbol(r["symbol"], prefix_map)
        out.append(row)
    return out


# ---------------------------------------------------------------------------
# TradingView classifications + tagged row builder
# ---------------------------------------------------------------------------

def _symbol_map_from_tv(tv_rows: list[dict[str, str]]) -> dict[str, str]:
    """bare -> exchange-prefixed map, tolerant of `.`/`-` (BRK-B vs BRK.B)."""
    out: dict[str, str] = {}
    for r in tv_rows:
        sym = r["symbol"]
        bare = sym.split(":", 1)[1] if ":" in sym else sym
        out[bare.replace("-", ".")] = sym
    return out


def get_tv_classifications(
    *,
    market: str = "america",
    exchanges: tuple[str, ...] = ("NYSE", "NASDAQ", "AMEX"),
) -> list[dict[str, str]]:
    """TradingView ICB-style sector/industry for all US stocks."""
    rows: list[dict[str, str]] = []
    for exch in exchanges:
        screen_rows, _ = screen(market=market, exchange=exch, columns=("sector", "industry"))
        for r in screen_rows:
            rows.append({
                "symbol": str(r["symbol"]),
                "sector": r["sector"] if r["sector"] is not None else "",
                "industry": r["industry"] if r["industry"] is not None else "",
            })
    return rows


def classification_rows(
    *,
    force_refetch: bool = False,
    exchanges: tuple[str, ...] = ("NYSE", "NASDAQ", "AMEX"),
) -> list[dict[str, str | None]]:
    """Union GICS + TV classifications, tagged by taxonomy, with refreshed_at.

    Derives the ``bare -> prefixed`` symbol map from the TV sweep itself
    (single ``screen()`` call per exchange — no second market sweep), then
    feeds it to ``get_gics_classifications`` so the GICS table's ``symbol``
    matches the form ``ohlcv`` stores.
    """
    from datetime import datetime, timezone

    tv = get_tv_classifications(exchanges=exchanges)
    symbol_map = _symbol_map_from_tv(tv)
    gics = get_gics_classifications(
        force_refetch=force_refetch, symbol_map=symbol_map
    )

    refreshed_at = datetime.now(timezone.utc).isoformat()
    rows: list[dict[str, str | None]] = []
    for r in gics:
        rows.append({
            "symbol": r["symbol"],
            "taxonomy": "gics",
            "sector": r["sector"],
            "industry_group": r["industry_group"],
            "industry": r["industry"],
            "sub_industry": r["sub_industry"],
            "security": r["security"],
            "refreshed_at": refreshed_at,
        })
    for r in tv:
        rows.append({
            "symbol": r["symbol"],
            "taxonomy": "tv",
            "sector": r["sector"],
            "industry_group": None,
            "industry": r["industry"],
            "sub_industry": None,
            "security": None,
            "refreshed_at": refreshed_at,
        })
    return rows
